version: '3.7'
services:
  web:
    build:
      context: ../
      dockerfile: src/Web/Dockerfile
    ports:
      - 9000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTP_PORT=9000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    networks:
      - network
    
  collection:
    build:
      context: ../
      dockerfile: src/CollectionService/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    networks:
      - network

  gateway:
    build:
      context: ../
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - 4000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTP_PORT=4000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    networks:
      - network
  
  identity:
    build:
      context: ../
      dockerfile: src/Identity/Dockerfile
    ports:
      - 10000:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTP_PORT=10000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    networks:
      - network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass44w0rd
      - MSSQL_TCP_ENABLED=1
      - MSSQL_TCP_PORT=1433
      - MSSQLNP_ENABLED=1
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - network
      
  #elasticsearch:
  #  container_name: elasticsearch
  #  image: elasticsearch:7.17.9
  #  restart: unless-stopped
  #  ports:
  #    - 9200:9200
  #  volumes:
  #    - elasticsearch-data:/usr/share/elasticsearch/data
  #  environment:
  #    - xpack.monitoring.enabled=true
  #    - xpack.watcher.enabled=false
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - discovery.type=single-node
  #  networks:
  #    - network

networks:
  network:

volumes:
  dbdata:
  elasticsearch-data:
