FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /
COPY ./src/CommonService/src/Common/Common.csproj ./CommonService/src/Common/
COPY ./src/Identity/Identity.csproj ./Identity/


COPY ./src/CommonService/src/Common ./CommonService/src/Common/
COPY ./src/Identity  ./Identity/


RUN ls
WORKDIR /Identity
RUN dotnet restore
RUN dotnet build  -c Release --no-restore ./Identity.csproj
RUN dotnet publish -c Release --no-build -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0

# Setup working directory for the project
WORKDIR /
COPY --from=build /Identity/out  .


ENTRYPOINT ["dotnet", "Identity.dll"]

