

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY ./Web/*.csproj ./
COPY ./CommonService/src/Common/Common.csproj ./CommonService/src/Common/

RUN dotnet restore ./CommonService/src/Common/Common.csproj
RUN dotnet restore ./Web.csproj

# copy everything else and build app
COPY . ./
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Web.dll"]
